#### general settings
name: resize_net
use_tb_logger: true
model: resize
distortion: sr
scale: 2
gpu_ids: [0]
scalea: 1
scaleb: 2

#### datasets

datasets:
  train:
    name: GT
    mode: GT
    dataroot_GT: /media/jianghao/Samsung_T5/dataset/clic/all # path to training HR images
    meta_info_file: /home/jianghao/Code/bytedance/DBC/codes/data/meta_info/clic.txt
    num_frame: 1
    n_workers: 8 # per GPU
    batch_size: 8
    color: RGB
    interval: 1
    scale: 2

  val:
    name: GT
    mode: GT
    dataroot_GT: /media/jianghao/Elements/datasets/kodak # path to validation HR images
    meta_info_file: /home/jianghao/Code/bytedance/DBC/codes/data/meta_info/kodak.txt
    num_frame: 1
    crop_border: 0
    interval: 1
    scale: 2

#### network structures

network_G:
  in_nc: 3
  out_nc: 3
  scale: 2
  init: xavier

#### path

path:
  pretrain_model_G: ~
  pretrain_model_A: ~
  resume_state: ~
  strict_load: False
#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 1e-4
  lr_A: !!float 1e-4
  beta1: 0.9
  beta2: 0.999
  niter: 2000000
  warmup_iter: -1 # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [1000000]
  lr_gamma: 0.3
  # lr_scheme: CosineAnnealingLR_Restart
  # T_period: [250000, 250000]
  # restarts: [250000]
  # restart_weights : [1]
  # eta_min: !!float 5e-6

  pixel_criterion_forw: l2
  pixel_criterion_back: l2

  manual_seed: 10

  val_freq: !!float 500

  lambda_fit_forw: 1
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 0
  gradient_clipping: 5
  gaussian_scale: 1

#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 500
