
#### general settings
name: PreProcess_x2
use_tb_logger: true
model: EDSR
distortion: sr
scale: 2
gpu_ids: [0]
scalea: 1
scaleb: 3

#### datasets

datasets:
  train:
    name: Vimeo90k
    mode: Vimeo90k
    dataroot_GT: /home/jianghao/Dataset/vimeo_septuplet/sequences # path to validation HR images
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    meta_info_file: /home/jianghao/Code/Graduation/4k1/codes/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    num_frame: 1
    n_workers: 8  # per GPU
    batch_size: 8
    color: RGB
    crop_border: 8

  val:
    name: Vimeo90k
    mode: Vimeo90k
    dataroot_GT: /home/jianghao/Dataset/vimeo_septuplet/test # path to validation HR images
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    meta_info_file: /home/jianghao/Code/Graduation/4k1/codes/data/meta_info/meta_info_Vimeo90K_test_GT.txt
    num_frame: 1
    crop_border: 8



#### network structures

network_G:
  in_nc: 3
  out_nc: 3
  scale: 2
  init: xavier


#### path

path:
  pretrain_model_G: ~ # /home/jianghao/Code/Graduation/4k1/experiments/models/60000_G.pth
  #  ~ # /home/jianghao/Code/Graduation/4k1/experiments/1000_G.pth
  pretrain_model_A: /home/jianghao/Code/Graduation/4k1/PreProcess_pth/1000_A.pth
  pretrain_model_C: ~
  resume_state: ~ # /home/jianghao/Code/Graduation/4k1/experiments/PreProcess_x2/training_state/10000.state
#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 1e-5
  beta1: 0.9
  beta2: 0.999
  niter: 500000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [200000, 300000, 350000, 400000]
  lr_gamma: 0.5

  pixel_criterion_forw: l1
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: !!float 500

  lambda_fit_forw: 1
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 0
  gradient_clipping: 50
  gaussian_scale: 1


#### logger

logger:
  print_freq: 10
  save_checkpoint_freq: !!float 500
# /home/gy4qf62/Invertible-Image-Rescaling/experiments/1000_A.pth