
#### general settings
name: PreProcess_x2_4k
use_tb_logger: true
model: EDSR
distortion: sr
scale: 2
gpu_ids: [1]
scalea: 1
scaleb: 2

#### datasets

datasets:
  train:
    name: 4k_video
    mode: 4k_video
    dataroot_GT: /home/jianghao/Dataset/4k_video/HR # path to validation HR images
    dataroot_LQ: /home/jianghao/Dataset/4k_video/LR_lanczos # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    dataroot_codec: /home/jianghao/Dataset/4k_video/HEVCQP22
    meta_info_file: /home/jianghao/Code/Graduation/4k1/codes/data/meta_info/meta_info_4kvideos_train.txt
    num_frame: 1
    n_workers: 8  # per GPU
    batch_size: 4
    color: RGB
    interval: 1
    scale: 2

  val:
    name: 4k_video
    mode: 4k_video
    dataroot_GT: /home/jianghao/Dataset/4k_video_test/HR # path to validation HR images
    dataroot_LQ: /home/jianghao/Dataset/4k_video_test/LR_lanczos # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    dataroot_codec:  /home/jianghao/Dataset/4k_video_test/HEVCQP22
    meta_info_file: /home/jianghao/Code/Graduation/4k1/codes/data/meta_info/meta_info_4kvideos_test.txt
    num_frame: 1
    crop_border: 24
    interval: 1
    scale: 2


#### network structures

network_G:
  in_nc: 3
  out_nc: 3
  scale: 2
  init: xavier


#### path

path:
  pretrain_model_G: /home/jianghao/Code/Graduation/4k1/experiments/models/94000_G.pth
  pretrain_model_A: /home/jianghao/Code/Graduation/4k1/experiments/models/94000_A.pth
  pretrain_model_C: ~
  resume_state: ~
#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 1e-4
  lr_A: !!float 1e-4
  beta1: 0.9
  beta2: 0.999
  niter: 500000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [100000, 200000, 300000, 400000]
  lr_gamma: 0.5
  # lr_scheme: CosineAnnealingLR_Restart
  # T_period: [250000, 250000]
  # restarts: [250000]
  # restart_weights : [1]
  # eta_min: !!float 5e-6

  pixel_criterion_forw: l1
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: !!float 500

  lambda_fit_forw: 1
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 0
  gradient_clipping: 50
  gaussian_scale: 1


#### logger

logger:
  print_freq: 10
  save_checkpoint_freq: !!float 500